tasks:
  - init: |
      yarn
    command: yarn dev
  - init: |
      sh -c "$(curl -sSfL https://release.solana.com/v1.8.5/install)"
      export PATH="/home/gitpod/.local/share/solana/install/active_release/bin:$PATH"
      solana config set --url https://api.devnet.solana.com
      mkdir solana-wallet
      solana-keygen new --outfile solana-wallet/keypair.json
      solana airdrop 1 $(solana-keygen pubkey solana-wallet/keypair.json)
    command: solana --version
      
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - jpoissonnier.vscode-styled-components
