tasks:
  - init: |
      yarn
    command: yarn dev
  - init: |
      sh -c "$(curl -sSfL https://release.solana.com/v1.8.5/install)"
    command: export PATH="/home/gitpod/.local/share/solana/install/active_release/bin:$PATH"
      
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - jpoissonnier.vscode-styled-components
