tasks:
  - init: |
      yarn
    command: yarn dev
  - command: sh -c "$(curl -sSfL https://release.solana.com/v1.8.5/install)"
  
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - jpoissonnier.vscode-styled-components
